Migrate: build-tool use vite replace vue-cli
radishes-music/radishes pull request #72
Opened 2023-10-29 09:41 UTC by little-buddy

| Step           | Status |
| -------------- | ------ |
| serve-web      | ✅      |
| build-web      | doing  |
| electron-build | doing  |
| build-cli      | doing  |

2023-11-07 09:28 UTC, Linkontoask commented
Any progress?

2023-11-07 16:11 UTC, little-buddy commented
It’s been a while, but I’m still working 💪🏻

2023-11-08 13:04 UTC, little-buddy commented
| Step           | Status |
| -------------- | ------ |
| serve-web      | ✅      |
| build-web      | ✅  |
| electron-build | doing  |
| build-ci      | doing  |

2023-11-08 13:17 UTC, little-buddy commented
| Step           | Status |
| -------------- | ------ |
| serve-web      | ✅      |
| build-web      | ✅  |
| electron-build | doing  |
| build-ci      | todo |

2023-11-12 13:32 UTC, little-buddy commented
Todo

2023-11-28 01:38 UTC, little-buddy commented
| Step           | Status |
| -------------- | ------ |
| serve-web      | ✅      |
| build-web      | ✅  |
| electron-build | ✅  |
| build-ci      | ✅   |

Now!!! 
`ci` can build on `macos`, but it is not adapted for other platforms. 
Except remove loading box, others workd fine.
🎸🎸🎸

2023-11-28 07:47 UTC, Linkontoask commented
> Step	Status
> serve-web	✅
> build-web	✅
> electron-build	✅
> build-ci	✅
> Now!!! `ci` can build on `macos`, but it is not adapted for other platforms. Except remove loading box, others workd fine. 🎸🎸🎸

Later I will try to see if the windows system is normal

2023-11-28 08:02 UTC, Linkontoask reviewed
cool

2023-11-28 08:02 UTC, Linkontoask commented on export-env.sh
> +echo "\033[32m ===================================================== \033[0m"
When will this script be invoked

2023-11-28 13:12 UTC, little-buddy commented on export-env.sh
> +echo "\033[32m ===================================================== \033[0m"
only run `yarn mirrori` in China for electron

2023-11-29 03:06 UTC, Linkontoask requested changes

2023-11-29 03:06 UTC, Linkontoask commented on package.json
> +    "pkg": "rm -rf dist-electron && yarn build:electron && npx electron-builder --config .electron-builder.config.js",
windows does not have the rm command, so you need to use rimraf to be compatible with different systems

2023-11-29 08:43 UTC, little-buddy commented on package.json
> +    "pkg": "npx rimraf dist-electron && yarn build:electron && npx electron-builder --config .electron-builder.config.js",
fix it @Linkontoask

2023-11-29 08:45 UTC, merged

2023-11-29 08:46 UTC, Linkontoask commented
🎉🎉🎉🎉🎉